spring:
  application:
    name: graphql-gateway
server:
  port: 8081

grpc:
  client:
    grpc-order:
      negotiation-type: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      # 方便本地调用，指定地址，调用到本地的rpc服务，线上需要注释，根据consul取实际地址
      address: static://127.0.0.1:6001
    grpc-customer:
      negotiation-type: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      # 方便本地调用，指定地址，调用到本地的rpc服务，线上需要注释，根据consul取实际地址
      address: static://127.0.0.1:6002